.gitlab-ci.yml
script/app-chaos
script/cassandra-app-deploy
script/chaos
script/gke
script/gke-cleanup
script/infra-setup
script/jenkins-app-deploy
script/mongo-app-deploy
script/percona-app-deploy
script/postgres-app-deploy
script/stateful-app-deploy

Added the Gitlab CI YAML and related scripts to run litmus jobs on the GKE platform.

Added the Gitlab CI YAML and related scripts to run litmus jobs on the GKE platform.

---

.gitlab-ci.yml
script/gke

- Update the docker image tag.
- Implement changes to the cluster creation script.

Update image tag of the docker build and fix script issues for GKE platform.

---

script/gke-cleanup

- Fix the cleanup script for GKE cluster.

Fix the cleanup script for GKE cluster.

---

script/gke-cleanup

- Provide the service account file path for the ansible module to execute.

Provide the service account file path for the ansible module to execute.

---

script/provider/infra-setup

This PR will update the openebs setup yaml wtih the commit based on build from the baseline file.
Signed-off-by: atulabhi <atulabhi@gmail.com>

updated script infra-setup

---

.gitlab-ci.yml
script/apps/memleak/tests/jiva/memory-consumption
script/apps/percona/functional/jiva/k8s-snapshot-clone

Signed-off-by: gprasath <giridhara.prasad@cloudbyte.com>
Included snapshot & clone creation test job into functional stage.
Added script that triggers the actual test of creating snapshot and clone.
Here is the pipeline result with the test included,
https://gitlab.openebs.ci/openebs/e2e-gke/pipelines/4330

Adding snapshot/clone creation and memory consumption test jobs into GKE pipeline

---

.gitlab-ci.yml

Fix typo memory consumption gitlab script

---

.gitlab-ci.yml
script/apps/prometheus/deployer/prometheus-app-deploy-cstor
script/apps/prometheus/functional/cstor/memcheck/memory-consumption
script/provider/setup-sc

- Include memory consumption test for cstor istgt
https://gitlab.openebs.ci/openebs/e2e-gke/pipelines/4726

Include memory consumption test for cstor istgt

---

.gitlab-ci.yml
script/apps/cassandra/functional/jiva/app-sts-replica-scale
script/apps/fio/tests/cstor/fio-volume-data-integrity-check

- Included data integrity check script for cstor
- modified jiva application replica scaleup playbook 
@ksatchit  @yudaykiran can you please review this PR

Included data integrity check script for cstor

---

.gitlab-ci.yml
script/apps/cassandra/deprovision/cassandra-app-deprovision-jiva
script/apps/cassandra/functional/jiva/app-sts-replica-scale
script/apps/jenkins/deprovision/jenkins-app-deprovision-jiva
script/apps/mongo/chaos/jiva/application-pod-failure
script/apps/mongo/deprovision/mongo-app-deprovision-jiva
script/apps/percona/deprovision/percona-app-deprovision-jiva
script/apps/postgres/deprovision/postgres-app-deprovision-jiva
script/apps/prometheus/deprovision/prometheus-app-deprovision-cstor

- Include APP-DEPROVISION stage to perform stateful app deprovisioning
https://gitlab.openebs.ci/openebs/e2e-gke/pipelines/4791

Include APP-DEPROVISION stage to perform stateful app deprovisioning

---

.gitlab-ci.yml

updated the deprovison stage in gitlab ci
@dargasudarshan can you please review this PR

refactor(yaml): Updated gitlab ci yaml 

---

.gitlab-ci.yml

refactor(yaml): Update gitlab ci loadgen job for cassandra

---

.gitlab-ci.yml

refactor(yaml) Include k8s snapshot test with 1replica

---

.gitlab-ci.yml
script/apps/percona/chaos/jiva/single-replica-failure
script/apps/percona/deployer/percona-app-deploy-cstor

Signed-off-by: gprasath giridhara.prasad@cloudbyte.com
- Included single replica failure executor script which runs against percona single replica deployment.
- Included the above job in chaos stage.

Including single replica failure in GKE pipeline

---

script/utils/litmus_job_runner

Signed-off-by: ksatchit <karthik.s@openebs.io>

(fix)(bash): fix the litmus job monitor logic

---

script/gke

- The wrong file was getting copied due to which cluster deletion was
failing.
- Removed the extra-vars of n1-standard-4 as it is the default now.

fix<script>: Copy the correct zone file for the cluster deletion to work.

---

script/provider/infra-setup

- Modified the e2e-infrastructure path in script

refactor(script): Modified the e2e-infrastructure path in infra setup script

---

.gitlab-ci.yml
script/apps/nuodb/deployer/nuodb-app-deploy-cstor

- Included deployment script of nuodb to pipeline

Included deployment script of nuodb to pipeline

---

script/apps/nuodb/deployer/nuodb-app-deploy-cstor

Update nuodb deploy script

---

.gitlab-ci.yml
script/apps/percona/functional/cstor/snapshot-rebuild-multiple-rep
script/apps/percona/functional/cstor/snapshot-rebuild-single-rep

**Following is the link of pipeline**:
https://gitlab.openebs.ci/openebs/e2e-gke/pipelines/318
**Special notes for reviewers**
- The test is failing for some reason. The fix for the test is under pr.

Include snapshot rebuild for gke-pipeline

---

.gitlab-ci.yml
script/gke
script/gke-cleanup
script/utils/setup_dependencies

Included path references to the gitlab scripts

---

.gitlab-ci.yml

- Included a check to get the pipeline source

Included a check to get the pipeline source

---

.gitlab-ci.yml
script/apps/cassandra/deprovision/cassandra-app-deprovision-cstor
script/apps/jenkins/deprovision/jenkins-app-deprovision-cstor
script/apps/mongo/deprovision/mongo-app-deprovision-cstor
script/apps/percona/deprovision/percona-app-deprovision-cstor

- Included the deprovisioning of cstor applications in pipeline
https://gitlab.openebs.ci/openebs/e2e-gke/pipelines/395

Included the script for deprovisioning of cstor application
